server:
  port: 8081

logging:
  level:
    root: info
    org.springframework.boot: info
    dev.cmartin.microserviceone: debug

management:
  endpoints:
    web:
      exposure:
        include: [ health,loggers,env ]