spring:
  application:
    name: "ms-one"
  devtools:
    restart:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /ms-one

logging:
  level:
    root: info
    dev.cmartin.microserviceone: debug
    org.springframework.web.server.adapter: debug
    org.springframework.boot: info

management:
  endpoints:
    web:
      exposure:
        include: [ health,loggers,env,mappings ]

service:
  countries:
    file: "countries.json"
